### ISSUE TITLE
[QUESTION] No general multivector class?

### ISSUE THREAD

**Issue by Ziriax** [jeremyong/klein#11]
I noticed that Klein doesn't have a multivector class (besides the one in the parser for testing).

Did you pick all the operators in such a way that a multivector is never an output?

If so, there must be things that cannot be done with Klein, or, maybe multi vectors are not needed for practical tasks?

Thanks again.

**Comment by jeremyong** [comment]
Multivectors do not, in general, have a useful geometric interpretation. This is actually what causes practitioners to distinguish "geometric algebra" from the "clifford algebra" it is a subalgebra of. Excluding the general multivector is a deliberate choice to reduce the amount of code needed to support what would be a less useful set of operations on the fuller algebra and discourage misuse. I'll close the issue but feel free to continue replying if you have questions :)

**Comment by Ziriax** [comment]
Thanks. If all the elements have geometric interpretations, do they also have geometric visualizations? It would be very useful for educational and debugging purposes to have e.g. Unity3D components and debug renderers for each struct. Easy to do for points, lines, planes, directions and branches, but I don't immediately know how to visualize rotors, motors, translators, and especially ideal lines, ideal planes, and duals.
