### ISSUE TITLE
Question about scaling

### ISSUE THREAD

**Issue by almarklein** [jeremyong/klein#13]
Hi, I've recently become interested in PGA, and am considering using it in a [new Python render engine](https://github.com/pygfx/pygfx). Math (especially this kind) is not my strong suit, but the advantages of PGA are compelling .... so I'm trying to wrap this up in a Python lib with an API suited for normal people :)

I'm now a bit stuck and I was hoping you could help. Render engines and 3D modeling tools usually provide 3 kinds of transforms for an object: translations, rotations, and scaling. I understand (more or less) how rotors and translators work, but I have not seen the use of scalors (if that's how you'd call them) anywhere. Is a scaling transform/motor even possible? What about anisotropic scaling?

*edit: if there's a better place to ask questions like these, please let me know, and I'll move the question there instead*

**Comment by almarklein** [comment]
A similar question has been asked (and answered) [here](https://discourse.bivector.net/t/scaling-with-pga/43)

**Comment by jeremyong** [comment]
:+1: You're always more than welcome to ask questions here or feel free to ping the [discord](https://discord.com/invite/6qg4QT) with questions as well.
