### ISSUE TITLE
Is branch a term for a line passing through the origin?

### ISSUE THREAD

**Issue by benhutchison** [jeremyong/klein#20]
Hi @jeremyong, nice library! 

Is *branch* generally accepted term for a line passing through the origin, or a name you chose? I couldn't find a wider confirmation of the term..

**Comment by jeremyong** [comment]
It's indeed my own term, loosely inspired by thinking of the branch of a logarithm (which shows up in GA). Sorry if it was confusing and thanks for the question! I actually struggled to come up with a suitable name here for some time and I'm still not convinced myself.

**Comment by benhutchison** [comment]
Not confusing.. I think "a line passing through the origin" needs a precise term, branch is as good as any other.

**Comment by benhutchison** [comment]
Actually, I noticed in "Geometrical Algebra for Computer Science" ch 2, they talk about a "homogeneous line" and a "nonhomogenous line". Pretty sure the adjective refers to the line, not the line's equation. I googled the terms and came up blank, but I think they may be meaning _a line through, or not through, the origin_.
