### ISSUE TITLE
Tests failed in Visual Studio 2019

### ISSUE THREAD

**Issue by DJuego** [jeremyong/klein#5]
Well. I built the tests without any problem in environment Windows 10 x64 with Microsoft Visual Studio 2019. 

By running them some are successfully passed on. For example, sym_test.exe.

![image](https://user-images.githubusercontent.com/1956212/82727290-7d2e9180-9ce1-11ea-8e1d-c3e80079551d.png)

However there are problems with klein_test.exe

![image](https://user-images.githubusercontent.com/1956212/82727343-d26aa300-9ce1-11ea-900e-04ed55815924.png)

DJuego

**Comment by jeremyong** [comment]
Looks like something broke specifically for the release version on Windows, will investigate. Can you confirm that compiled with the Debug configuration that the tests pass?

**Comment by DJuego** [comment]
Sorry! @jeremyong  You're absolutely right. The compilation I used was "release" configuration With "debug" configuration  all the tests pass without a hitch.  :-) This issue can be closed. 

DJuego

PS: The compilation/building does not give problems. :-)

**Comment by jeremyong** [comment]
I’m going to reopen actually because it is definitely an unexpected result for me (the release configuration should pass without any failures as well) but thanks for confirming!

**Comment by DJuego** [comment]
I can confirm that this error has also been fixed in the **release** configuration. Now the tests are passed.  Thank you!

DJuego
