### ISSUE TITLE
Euler angles for Klein?

### ISSUE THREAD

**Issue by DJuego** [jeremyong/klein#6]
Suggestion:

It seems interesting that, if possible, Klein supports Euler's angles "natively" in both directions (Euler <=> Klein). The representation in Euler angles (yaw, pitch, row, etc)  tends to be more intuitive and understandable. At least visually. And it would also improve interoperability of _klein_ with other libraries.  

DJuego

**Comment by jeremyong** [comment]
Now done as of most recent commit, thanks for the suggestion
