### ISSUE TITLE
Small typo in doc?

### ISSUE THREAD

**Issue by Ziriax** [jeremyong/klein#9]
I think the [following comment](https://github.com/jeremyong/klein/blob/9b3e525ce4b5b9b09616bb3eb6918523f50a1042/public/klein/line.hpp#L240) should be:

```
a \mathbf{e}_{23} + b\mathbf{e}_{31} + c\mathbf{e}_{12}
```

So basically

```
a e₂₃ + b e₃₁ + c e₁₂
```

Is this correct?

**Comment by jeremyong** [comment]
Yup that's definitely a typo thanks!
